
<div id="onestepcheckout-login-popup" style="display:none;" >
    <div class="onestepcheckout-popup-wrapper">
        <div class="onestepcheckout-popup-contents">
            <div id="onestepcheckout-login-popup-contents-forgot" style="display: none;">
                <h1><?php echo $this->__('Forgotten your password?'); ?></h1>
                <p class="title-forgot"><?php echo $this->__('Please enter your email below and we will send you a new password.'); ?></p>
				<p class="close"><a href="javascript:void(0);"><?php echo $this->__('X'); ?></a></p>
                <form id="onestepcheckout-forgot-form">

                    <div id="onestepcheckout-forgot-loading" style="display: none;" class="loading-ajax-login">&nbsp;</div>
                    <div id="onestepcheckout-forgot-error" class="onestepcheckout-error" style="display: none;">&nbsp;</div>
                    <div id="onestepcheckout-forgot-success" style="display: none;">
                        <!--2014.18.11 update start-->
                        <?php echo $this->__('We have now sent you a new password to your email address.'); ?>
                        <!--2014.18.11 update end-->
                    </div>

                    <ul id="onestepcheckout-forgot-table">						
						                          				
						<li>
							<label class="required" for="id_onestepcheckout_email"><?php echo $this->__('Email address'); ?> <span class="required">*</span></label>					
							<input type="text" class="input-text required-entry validate-email" name="onestepcheckout_email" id="id_onestepcheckout_email" />
						</li>
						<li class="last">
							<p><a href="javascript:void(0);" id="onestepcheckout-return-login-link"><span>&nbsp;</span><?php echo $this->__('Return to login'); ?></a></p>
							<button class="button" id="onestepcheckout-forgot-button" type="button"><?php echo $this->__('Send password'); ?></button>
						</li>  
                    </ul>
                </form>
                
            </div>

            <div id="onestepcheckout-login-popup-contents-login">

                <h1><?php echo $this->__('Login'); ?></h1>
				<p class="close"><a href="javascript:void(0);"><?php echo $this->__('X'); ?></a></p>
                <!--p><?php echo $this->__('Please login with your email address and password.'); ?></p-->
				<form id="onestepcheckout-login-form">

					<div id="onestepcheckout-login-loading" style="display: none;" class="loading-ajax-login">&nbsp;</div>
					<div id="onestepcheckout-login-error" class="onestepcheckout-error" style="display: none;">&nbsp;</div>

					<ul id="onestepcheckout-login-table">
						<li>
							<div class="input-box">
								<label class="required" for="id_onestepcheckout_username"><?php echo $this->__('Email address'); ?> <span class="required">*</span></label>
								<input tabindex="100" type="text" class="input-text required-entry validate-email" name="onestepcheckout_username" id="id_onestepcheckout_username" />
							</div>
					
						</li>
						<li>
							<div class="input-box">
								<label class="required" for="id_onestepcheckout_password"><?php echo $this->__('Password'); ?> <span class="required">*</span></label>
								<input type="password" tabindex="101" name="onestepcheckout_password" class="input-text required-entry validate-password" id="id_onestepcheckout_password" />
							</div>
						</li>
						<li class="last">
						  <button class="button" tabindex="102" id="onestepcheckout-login-button" type="button"><?php echo $this->__('Login'); ?></button>
						</li>
					</ul>
				</form>
                <p class="forgot-link"><a href="javascript:void(0);" id="onestepcheckout-forgot-password-link"><span>&nbsp;</span><?php echo $this->__('Forgotten your password?'); ?></a></p>
            </div>           
        </div>
    </div>
    
</div>
<?php //die('Michael');?>
<script>
var onestepcheckout_login_popup;
var login_popup;
Event.observe(window, 'load', function() {
    var options = {
        forgot_password_url: '<?php echo $this->getUrl('onestepcheckout/ajax/forgotPassword', array('_secure'=>true)); ?>',
        login_url: '<?php echo $this->getUrl('onestepcheckout/ajax/login', array('_secure'=>true)); ?>',
        translations: {
            invalid_email: '<?php echo $this->__('Please enter a valid email address'); ?>',
            email_not_found: '<?php echo $this->__('Please enter a registered email address.'); ?>'
        }
    };
    onestepcheckout_login_popup = new OneStepCheckoutLoginPopup(options);
    login_popup = onestepcheckout_login_popup;
});
</script>