<?php
/**
 * @category     Inchoo
 * @package     Inchoo Featured Products
 * @authors    Mladen Lotar <mladen.lotar@surgeworks.com>, Vedran Subotic <vedran.subotic@surgeworks.com>
 */
?>
<?php if(Mage::getModel('catalog/layer')->getCurrentCategory()->getCategoryLanding()=='71'):?>
	<?php
		$_productCollection=$this->getFeaturedProductCollection();
		$_helper = $this->helper('catalog/output');
	?>
	<?php if(!$_productCollection->count()): ?>
		<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
	<?php else: ?>
		<div id="cat_fp">
		<h2>Featured product<?php if ($_productCollection->count() > 1) echo 's';?></h2>
		<?php $_collectionSize = 3;//$_productCollection->count() ?>
		<?php $_columnCount = 3;//$this->getColumnCount(); ?>
		<div class="category-products">
	<?php $i=0; foreach ($_productCollection as $_product): ?>
		<?php if($_library ==1 ) : ?> 
			<script type="text/javascript">
				jQuery.noConflict();
				(function(jQuery) {
				
				  jQuery(function() {
					jQuery("#various<?php echo $_product->getId(); ?>").fancybox({
					
							'autoScale'			: true,
							'transitionIn'		: 'none',
							'transitionOut'		: 'none',
							'type'				: 'iframe'
							<?php if($_isModal==="true") { ?>
							,'modal'			    : true
							<?php } ?>
						});
				  });
				})(jQuery);
			</script>
		<?php endif ?>
    
        <?php if ($i++%$_columnCount==0): ?>
        	<ul class="products-grid">
        <?php endif ?>
           
		<li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
			<a id="mover<?php echo $_product->getId(); ?>" href="<?php echo $_product->getProductUrl() ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(240,200); ?>" width="240" height="200" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
				
			<script type="text/javascript">
				jQuery("#mover<?php echo $_product->getId(); ?>").hover(function(){
					 jQuery('#thickbox<?php echo $_product->getId(); ?>').toggle();
				});
				jQuery("#various<?php echo $_product->getId(); ?>").hover(function(){
					 jQuery('#thickbox<?php echo $_product->getId(); ?>').toggle();
				});
			</script>
			<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
			<div class="product-price">
				<?php echo $this->getPriceHtml($_product, true) ?>
			</div>
        </li>
        
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        	</ul>
        <?php endif ?>
    <?php endforeach ?>
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
</div>

		</div>
	<?php endif; ?>
<?php endif ?>