<?php  $_order = $this->getOrder() ?>
<?php if ( ($msg = $this->getMessagesBlock()->getGroupedHtml()) && $msg != null): ?>
	<?php echo  $msg;?>
<?php else: ?>
<div class="page-title title-buttons">
	<h1><?php echo $this->__('Order #%s - %s', $_order->getRealOrderId(), $_order->getStatusLabel()) ?></h1>
</div>
<p class="order-date"><?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?></p>
<?php if (!$_order->getIsVirtual()): ?>
<div class="col2-set order-info-box">
	<div class="col-1">
		<div class="box">
			<div class="box-title">
				<h2><?php echo $this->__('Shipping Address') ?></h2>
			</div>
			<div class="box-content">
				<address><?php echo $_order->getShippingAddress()->format('html') ?></address>
			</div>
		</div>
	</div>
	<div class="col-2">
		<div class="box">
			<div class="box-title">
				<h2><?php echo $this->__('Shipping Method') ?><?php /* | <a href="#"><?php echo $this->__('Track Order') ?></a>*/ ?></h2>
			</div>
			<div class="box-content">
				<?php if ($_order->getShippingDescription()): ?>
					<?php echo $_order->getShippingDescription() ?>
				<?php else: ?>
					<p><?php echo $this->helper('sales')->__('No shipping information available'); ?></p>
				<?php endif; ?>
			</div>
		</div>
	</div>
</div>
<?php endif; ?>
<div class="col2-set order-info-box">
	<div class="col-1">
		<div class="box">
			<div class="box-title">
				<h2><?php echo $this->__('Billing Address') ?></h2>
			</div>
			<div class="box-content">
				<address><?php echo $_order->getBillingAddress()->format('html') ?></address>
			</div>
		</div>
	</div>
	<div class="col-2">
		<div class="box box-payment">
			<div class="box-title">
				<h2><?php echo $this->__('Payment Method') ?></h2>
			</div>
			<div class="box-content">
				<?php echo $this->getPaymentInfoHtml() ?>
			</div>
		</div>
	</div>
</div>
<?php endif;?>