<div id="onestepcheckout-payment-methods" class="onestepcheckout-payment-methods">
	<dl class="sp-methods" id="checkout-payment-method-load">
	<?php $i=0;?>
	<?php foreach ($this->getMethods() as $_method): $_code = $_method->getCode() ?>
	<?php $i++;?>
	<?php if($i != count($this->getMethods())):?>
		<style type="text/css">
			#advice-validate-one-required-by-name-p_method_<?php echo $_code ?>{
				display: none !important;
			}
		</style>
	<?php endif;?>
		<dt>
		<?php if( sizeof($this->getMethods()) > 1 ): ?>	
				<input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" onclick="save_shipping_method(shipping_method_url,0,update_payment_review);" <?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> class="radio validate-one-required-by-name" />
		<?php else: ?>
				<span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" class="radio validate-one-required-by-name " onclick="save_shipping_method(shipping_method_url,0,update_payment_review);" /></span>
		<?php endif; ?>
				<label id="p_label_<?php echo $_code ?>" for="p_method_<?php echo $_code ?>"><?php echo $this->htmlEscape($_method->getTitle()) ?> <?php echo $this->getMethodLabelAfterHtml($_method) ?></label>
		</dt>
		<?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
		<dd id="container_payment_method_<?php echo $_code; ?>" class="payment-method">
				<?php echo $html; ?>
		</dd>
		<?php endif; ?>
	<?php endforeach; ?>
	</dl>
	
	<!--Gift Card Block-->
	
	<?php if( Mage::getStoreConfig('giftcard/giftcard/enabled', Mage::app()->getStore()->getStoreId())):?>
<?php 
$currentCustomer =Mage::getSingleton('customer/session')->getCustomer();
$collection =Mage::getModel('kartparadigm_giftcard/giftcard')->getCollection()
		->addFieldToFilter('receiver_mail',$currentCustomer->getEmail())
		->addFieldToFilter('giftcard_status',1)
		->addOrder('giftcard_id','DESC');
		?>
<div class="giftcard">
    <h2 style="margin-left:0; margin-right:0; margin-top:10px;"><?php echo $this->__('Pay with Gift Card') ?></h2>
	<div id="giftcard_balance_lookup"></div>
	<span id="gcadd-please-wait" class="please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo $this->__('Please wait, loading...') ?>
    </span>
    <span id="gc-please-wait" class="please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo $this->__('Please wait, loading...') ?>
    </span>
	<form id="discount-form" action="<?php echo $this->getUrl('giftcard/index/index') ?>" method="post">
   		<fieldset>
       		<?php if(Mage::getSingleton('customer/session')->isLoggedIn()):?>
                    
                    <?php $quote=Mage::getSingleton('checkout/session')->getQuote();
                    $appliedcodes=$quote->getGiftcardCode();?>
                   
                    <?php if($collection->count()>0):?>
                        <!--<select name="gccodes" id="gccodes" class="validate-select" title="Giftcard">
                        <option value=""> <?php echo $this->__('Select Giftcard Code')?> </option>
                        <?php foreach($collection as $coll):
                        if (strpos($appliedcodes,$coll->getGiftcardCode()) !== false)
   				      continue;?>
                        <option value="<?php echo $coll->getGiftcardCode().','.$coll->getGiftcardBal();?>"><?php echo $coll->getGiftcardCode()." (".Mage::helper('core')->currency($coll['giftcard_bal']).")";?>
                <?php endforeach;?>
                </option></select>  -->               
                <?php endif;?> 
                <?php endif;?>
            <input type="hidden" name="remove" id="remove-coupone" value="0" />
            <div class="v-fix"><input class="input-text" id="gc_code" name="gc_code" value="" placeholder="Gift card number" /></div>
           
<?php
if (Mage::getStoreConfig('giftcard/giftcard/customamt_select', Mage::app()->getStore()->getStoreId())) {
    echo "<br/>".$this->__('Redeem Amount')." : <input class='input-text required-entry' id='redeem_amt' name='redeem_amt'  />";
}
?>

<button class="button" onclick="addGiftCard1();" type="button" value="<?php echo $this->__('Apply Gift Card') ?>"><span><span style="text-transform:none;"><?php echo $this->__('Apply Gift Card') ?></span></span></button>
</fieldset>
</form>
<div style="margin-top:10px;">
<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
</div>
<?php
if (Mage::getSingleton('checkout/session')->getQuote()->getGiftcardBalused() != 0): ?>
<form action="<?php echo $this->getUrl('giftcard/index/cancel') ?>" method="post">

<?php
    $gccodes = explode(",", Mage::getSingleton('checkout/session')->getQuote()->getGiftcardCode());
    $gcbals = explode(",", Mage::getSingleton('checkout/session')->getQuote()->getGiftcardBal());
    $gcbalused = explode(",", Mage::getSingleton('checkout/session')->getQuote()->getGiftcardBalused());
    $i = 0;
    foreach($gccodes as $gccode) {
        echo "<h5 style='color:green'>".$this->__('Code').": " . $gccode .$this->__('  Net Bal') ." : " . Mage::helper('core')->currency($gcbals[$i] - $gcbalused[$i], true, false) . "</h5>";
		echo "<h5 style='color:green'>".$this->__('  Applied Amount') ." : " . Mage::helper('core')->currency($gcbalused[$i], true, false) . "</h5>";
        $i++;
    }
?>

<button class="button" onclick="cancelGiftCard();" type="button" value="<?php echo $this->__('Cancel Gift Card') ?>"><span><span style="text-transform:none;"><?php echo $this->__('Cancel Gift Card') ?></span></span></button>
</form>
<?php
endif; ?>
</div>
<?php endif;?>

	<!--End of Gift Card Block-->
</div>
<div class="tool-tip" id="payment-tool-tip" style="display:none;">
	<div class="btn-close"><a href="#" id="payment-tool-tip-close" title="<?php echo $this->__('Close') ?>"><?php echo $this->__('Close') ?></a></div>
	<div class="tool-tip-content"><img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>" /></div>
</div>
<script type="text/javascript">
//<![CDATA[
$$('#checkout-payment-method-load dt input').invoke('observe', 'click', function(e) {
    var element = e.element();
    var name = 'payment_form_' + element.value;
    
    /* Hide all other forms */
    $$('dd.payment-method').invoke('hide');
    
    if(element.checked) {
        var form = $(name);
        var container = $('container_payment_method_' + element.value);

        if(element !== null && container !== null)    {
            container.show();
            if(container == $('container_payment_method_paypaluk_express')){
                    $('payment_form_paypaluk_express_dupe').show();
                }else{
                    $('payment_form_paypaluk_express_dupe').hide();
                }
            $(name).show();
        }
    }    
});
//]]>
</script>
<script type="text/javascript">
//<![CDATA[
	function toggleToolTip(event){
		if($('payment-tool-tip')){
			$('payment-tool-tip').setStyle({
				top: (Event.pointerY(event)-560)+'px'//,
				//left: (Event.pointerX(event)+100)+'px'
			})
			$('payment-tool-tip').toggle();
		}
		Event.stop(event);
	}
	if($('payment-tool-tip-close')){
		Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
	}
	
	initWhatIsCvvListeners();	
//]]>
</script>
<script type="text/javascript">
jQuery('#giftcard_amount').html('<?php echo $giftcardamount; ?>');
</script>

<script src="<?php echo $this->getSkinUrl('js/giftcard/jquery.min-1.11.1.js')?>"></script>  
<script type="text/javascript">
var cgc=$.noConflict();
cgc(document).ready(function() {
     cgc("#gccodes").change(function() {
          var gcdata = cgc('option:selected',cgc(this)).val().split(",");
          cgc("#gc_code").val(gcdata[0]);
            cgc("#redeem_amt").val(gcdata[1]);
        });
        });
        </script>



 <script type="text/javascript">
        //<![CDATA[
        var giftcardForm1 = new VarienForm('discount-form');
        function checkGiftCardStatus()
        {
            if (giftcardForm1.validator && !giftcardForm1.validator.validate()) {
                return false;
            }
		
            new Ajax.Updater(
            'giftcard_balance_lookup',
            {
                onCreate: function() { $('gc-please-wait').show(); },
                onComplete: function() { $('gc-please-wait').hide(); },
                parameters : {gc_code : $('gc_code').value}
            }
        );
        }
	
	
        function addGiftCard1()
        {
            if (giftcardForm1.validator && !giftcardForm1.validator.validate()) {
                return false;
            }
            if($('gc_code').value == ""){
                alert("Enter valid Gift card code to proceed!");
                return false;
            }
            new Ajax.Updater(
            'giftcard_balance_lookup',
            '/giftcard/index/addindex/',
            {
                onCreate: function() { paymentLoad(); },
                onComplete: function() { 
                    paymentShow();
                    // adding progress block reload to pick up gift card addition
                    //checkout.reloadProgressBlock();
                    save_shipping_method(shipping_method_url, 1, 1, 1);
                    // if the grand total with the card is 0, hide the other payment methods
                    
                    //$('gc_code').value = "";
                },
                parameters : {gc_code : $('gc_code').value}
            }
        );
        }
		
		function cancelGiftCard()
        {
           
            new Ajax.Updater(
            'giftcard_balance_lookup',
            '/giftcard/index/cancelcard/',
            {
                onCreate: function() { paymentLoad(); },
                onComplete: function() { 
                    paymentShow();
                    // adding progress block reload to pick up gift card addition
                    //checkout.reloadProgressBlock();
                    save_shipping_method(shipping_method_url, 1, 1, 1);
					save_payment_method(payment_method_url, 1, 1, 1);
                    // if the grand total with the card is 0, hide the other payment methods
                    
                    //$('gc_code').value = "";
                },
                parameters : {gc_code : $('gc_code').value}
            }
        );
        }

        function disableNonFreePayments() {
		
            Form.getElements('checkout-payment-method-load').each(function(elem){
                if (elem.name == 'payment[method]' && elem.value == 'free') {
                    elem.checked = true;
                    elem.disabled = false;
                    elem.parentNode.show();
                } else {
                    elem.parentNode.disabled = true;
                    elem.parentNode.hide();
                }
            });
        
            document.getElementById('container_payment_method_paypaluk_express').hide();
        }
	
	
        function checkForZeroTotal() {
            var gc_update = new Ajax.Request(
            '/gateway/index/zerosubtotal', {
                method:'get',
                onSuccess: function(transport) {
                    var data = transport.responseText.evalJSON();
                    if (data.is_zero) {						
                        //$('checkout-payment-method-load').insert('<dt id="freepay"><input id="p_method_free" value="free" type="radio" name="payment[method]" title="No Payment Information Required" onclick="payment.switchMethod(\'free\')" class="radio"><label for="p_method_free">No Payment Information Required </label></dt>');
                        disableNonFreePayments();

                    }
                }
            }
        );
        }
	
	
        //]]>
    </script>