<div class="giftcard">
    <h2><?php echo $this->__('Pay with Gift Card') ?></h2>
    <div id="giftcard_balance_lookup"></div>
	 <span id="gcadd-please-wait" class="please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo $this->__('Please wait, loading...') ?>
    </span>
    <span id="gc-please-wait" class="please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo $this->__('Please wait, loading...') ?>
    </span>
	
	 <form id="giftcard-form" action="<?php echo $this->getUrl('enterprise_giftcardaccount/cart/add') ?>" method="post">
        <fieldset>
            <label for="giftcard_code"><?php echo $this->__('Gift card number') ?></label>
            <div class="v-fix"><input class="required-entry input-text" id="giftcard_code" name="giftcard_code" value="" /></div>
            <button class="button" onclick="addGiftCard();" type="button" value="<?php echo $this->__('Apply Gift Card') ?>"><span><span><?php echo $this->__('Apply Gift Card') ?></span></span></button>
           <?php /* <button class="button check-gc-status" onclick="checkGiftCardStatus();" type="button" value="<?php echo $this->__('Check Gift Card status and balance') ?>"><span><span><?php echo $this->__('Check Gift Card status and balance') ?></span></span></button> */?>
        </fieldset>
    </form>
	
    <script type="text/javascript">
    //<![CDATA[
    var giftcardForm = new VarienForm('giftcard-form');
    function checkGiftCardStatus()
    {
        if (giftcardForm.validator && !giftcardForm.validator.validate()) {
            return false;
        }
		
        new Ajax.Updater(
            'giftcard_balance_lookup',
            '<?php echo Mage::getUrl('enterprise_giftcardaccount/cart/quickCheck') ?>',
            {
                onCreate: function() { $('gc-please-wait').show(); },
                onComplete: function() { $('gc-please-wait').hide(); },
                parameters : {giftcard_code : $('giftcard_code').value}
            }
        );
    }
	
	
	function addGiftCard()
    {
        if (giftcardForm.validator && !giftcardForm.validator.validate()) {
            return false;
        }
        new Ajax.Updater(
            'giftcard_balance_lookup',
            '/giftcard/cart/quickAdd/',
            {
                onCreate: function() { $('gcadd-please-wait').show(); },
                onComplete: function() { 
                	$('gcadd-please-wait').hide(); 
					// adding progress block reload to pick up gift card addition
                	
                	// if the grand total with the card is 0, hide the other payment methods
                	checkForZeroTotal();					
					$('giftcard_code').value = "";
                },
                parameters : {giftcard_code : $('giftcard_code').value}
            }
        );
    }
	
	
	function disableNonFreePayments() {
		
		Form.getElements('multishipping-billing-form').each(function(elem){
            if (elem.name == 'payment[method]' && elem.value == 'free') {
                elem.checked = true;
                elem.disabled = false;
                elem.parentNode.show();
            } else {
                elem.parentNode.disabled = true;
                elem.parentNode.hide();
            }
        });
		
	}
	
    //]]>
    </script>
</div>
