<?php if($this->getProductId()!=''):?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>

<script type="text/javascript">
    //var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view product-quickconnect">
    <div class="product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_kdform"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>

        <div class="product-shop">
            <div class="product-main-info">
				<div class="product-name">
					<h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
				</div>
				<?php if ($_product->getDesignedBy() || $_product->getManufacturer()):?>
					<div class="product-specification">
					<?php if ($_product->getDesignedBy()):?>
						<div style="float:left"><?php echo $this->__('Designed by');?></div>
						<div class="product-designed-by">
							<?php echo $_helper->productAttribute($_product, nl2br($_product->getDesignedBy()), 'designed_by') ?>
						</div>
					<?php endif;?>
					<?php if ($_product->getDesignedBy() || $_product->getManufacturer()):?><div class="separator-line">|</div><?php endif;?>
					<?php if ($_product->getManufacturer()):?>
						<div class="product-brand">
							<?php echo $_product->getAttributeText('manufacturer'); ?>
						</div>
					<?php endif;?>						
					</div>
				<?php endif;?>	
				<div class="price-area">
				<?php echo $this->getPriceHtml($_product) ?>
				<p class="product-ids"><?php echo $this->__('<lablel>SKU:</lablel> %s', $this->escapeHtml($_product->getSku())); ?></p>
				</div>
				<?php if ($_product->isSaleable() && $this->hasOptions() && $this->getChildChildHtml('container1') ):?>
					<div class="options-container-small">
						<?php echo $this->getChildChildHtml('container1', '', true, true) ?>
					</div>
				<?php endif;?>
				<?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
				<?php echo $this->getChildHtml('alert_urls') ?>
				
			</div>
			
			<?php if (!$this->hasOptions()):?>
				<?php echo $this->getChildHtml('product_type_data') ?>
				<div class="add-to-box">
					<?php if($_product->isSaleable()): ?>
						<?php echo $this->getChildHtml('addtocart') ?>
					<?php endif; ?>
					<?php //echo $this->getChildHtml('addto') ?>
				</div>
			<?php else:?>
				<?php echo $this->getChildHtml('product_type_data') ?>
				<?php echo $this->getChildHtml('addto') ?>
			<?php endif; ?>
			<div class="full-detail"><a href="<?php echo $_product->getProductUrl();?>">View Full Product Detail</a></div>
        </div>

        <div class="product-img-box">
            <?php echo $this->getChildHtml('media') ?>
        </div>

        <div class="clearer"></div>
        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
			<?php //echo $this->getLayout()->getBlock('product.info.options.wrapper')->toHtml();?>
			<?php //echo $this->getLayout()->getBlock('product.info.options.wrapper.bottom')->toHtml();?>
            <?php //echo $this->getChildChildHtml('container2', '', true, true) ?>
        <?php endif;?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartKdForm = new VarienForm('product_addtocart_kdform');
        productAddToCartKdForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartKdForm);

        productAddToCartKdForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartKdForm);
    //]]>
    </script>
    </div>
</div>
<?php else:?>
Incorrect Product Details
<?php endif;?>