

<?php
	if($this->isAudienceEnable()):
		if($this->getAudienceCode()):
		?>
			<script>(function() {
				var _fbq = window._fbq || (window._fbq = []);
				if (!_fbq.loaded) {
					var fbds = document.createElement('script');
					fbds.async = true;
					fbds.src = '//connect.facebook.net/en_US/fbds.js';
					var s = document.getElementsByTagName('script')[0];
					s.parentNode.insertBefore(fbds, s);
					_fbq.loaded = true;
				}
				_fbq.push(['addPixelId', '<?php echo $this->getAudienceCode(); ?>']);
				})();
				window._fbq = window._fbq || [];
				window._fbq.push(['track', 'PixelInitialized', {}]);
				window._fbq.push(['track', 'ViewContent']);
				window._fbq.push(['track', 'Search']);
				window._fbq.push(['track', 'AddToCart']);
				window._fbq.push(['track', 'AddToWishlist']);
				window._fbq.push(['track', 'InitiateCheckout']);
				window._fbq.push(['track', 'AddPaymentInfo']);
				window._fbq.push(['track', 'Purchase', {value: '0.00', currency: 'USD'}]);
			</script>
			<noscript>
				<img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?id=<?php echo $this->getAudienceCode(); ?>&amp;ev=PixelInitialized" />
			</noscript>
		<?php
		endif;
	endif;
?>

<?php 
	if($this->getPageName() == 'purchase'):
		if($this->isTrackingEnable()):
			if($this->getTrackingCode()):
			?>
				<!-- Facebook Conversion Code for Test -->
				<script>
					(function() {
						var _fbq = window._fbq || (window._fbq = []);
						if (!_fbq.loaded) {
							var fbds = document.createElement('script');
							fbds.async = true;
							fbds.src = '//connect.facebook.net/en_US/fbds.js';
							var s = document.getElementsByTagName('script')[0];
							s.parentNode.insertBefore(fbds, s);
							_fbq.loaded = true;
						}
					})();
					window._fbq = window._fbq || [];
					window._fbq.push(['track', '<?php echo $this->getTrackingCode(); ?>', {'value':'<?php echo $this->getOrderValue(); ?>','currency':'<?php echo $this->getCurrency();?>'}]);
				</script>
				<noscript>
					<img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?ev=<?php echo $this->getTrackingCode();; ?>&amp;cd[value]=<?php echo $this->getOrderValue(); ?>&amp;cd[currency]=<?php echo $this->getCurrency();?>&amp;noscript=1" />
				</noscript>
			<?php
			endif;
		endif;
	endif;
?>



