<!-- Start AddToMyRegistry Tag -->
<div id="MyRegistryWidgetApiContainer" siteKey="D-Vizmh-TfLPX5XEpeKeeQ2" hasCustmized="true" isWidgetLoaded="0" urlTagID="registry-url" imageSrc="amasty_zoom" title="h1#registry-product-detailed-title" 
storeName="" storeLogo="" signUpLogo="" tryPriceCheck="false" price="registry-product-price" currency="27" 
quantity="" size="" sizeControl="" color="" colorControl="" category="" notes="" notesControl="" onGiftAdded="" 
description="" hideSize="false" hideColor="false">
    <img src="http://static.myregistry.com/merchants/mids00k/1492/AddButton/MrAddToRegistryButton_1492.jpg" style="border:0px; cursor: pointer;">
</div>
<script id='MyRegistryWidgetApiScript' type='text/javascript' src="//www.myregistry.com/WidgetScriptSet/MerchantWidgetButtonScript.js?versionInfo=1.0&buttonType=0"></script>
<!-- End AddToMyRegistry Tag -->  